#!/bin/sh
# Entrypoint script for ClamAV REST service
#
# Security: Runs virus definition updates and daemons as root,
# then drops privileges to 'scanner' user for the REST service.
#
# - Generates clamd.conf from environment variables
# - Updates virus definitions on startup
# - Starts clamd daemon for fast scanning
# - Drops privileges and starts the REST API server

set -e

# =============================================================================
# Generate ClamAV configuration files from environment variables
# =============================================================================
MAX_EXTRACTED_SIZE_MB=${MAX_EXTRACTED_SIZE_MB:-1024}
MAX_SINGLE_FILE_MB=${MAX_SINGLE_FILE_MB:-256}
MAX_RECURSION=${MAX_RECURSION:-16}
# MaxThreads controls concurrent scanning - increase for high throughput
MAX_THREADS=${MAX_THREADS:-20}

# Config file paths - stored in /var/run/clamav to preserve /etc/clamav/certs
CLAMD_CONF=/var/run/clamav/clamd.conf
FRESHCLAM_CONF=/var/run/clamav/freshclam.conf

echo "Generating ClamAV configuration files..."
echo "  MaxScanSize: ${MAX_EXTRACTED_SIZE_MB}M"
echo "  MaxFileSize: ${MAX_SINGLE_FILE_MB}M"
echo "  MaxRecursion: ${MAX_RECURSION}"

# Generate clamd.conf
cat > ${CLAMD_CONF} << EOF
# ClamAV daemon configuration
# Generated by entrypoint.sh from environment variables

# Network settings - only listen on localhost
TCPSocket 3310
TCPAddr 127.0.0.1

# Run as clamav user
User clamav

# Database location
DatabaseDirectory /var/lib/clamav

# Logging
LogFile /var/log/clamav/clamd.log
LogTime yes
LogVerbose no

# Scan limits - derived from environment variables
MaxScanSize ${MAX_EXTRACTED_SIZE_MB}M
MaxFileSize ${MAX_SINGLE_FILE_MB}M
MaxRecursion ${MAX_RECURSION}

# Concurrency - critical for high throughput
MaxThreads ${MAX_THREADS}

# Other limits
MaxDirectoryRecursion 20
StreamMaxLength ${MAX_SINGLE_FILE_MB}M
EOF

# Generate freshclam.conf
cat > ${FRESHCLAM_CONF} << EOF
# Freshclam configuration
# Generated by entrypoint.sh

# Database location
DatabaseDirectory /var/lib/clamav

# Update settings
DatabaseMirror database.clamav.net
NotifyClamd ${CLAMD_CONF}

# Logging
LogTime yes
LogVerbose no
EOF

echo "ClamAV configuration files generated."

# =============================================================================
# Start services
# =============================================================================

echo "Updating ClamAV virus definitions..."
freshclam --config-file=${FRESHCLAM_CONF} --stdout || echo "Warning: freshclam update failed (continuing with existing definitions)"

echo "Starting clamd daemon..."
clamd --config-file=${CLAMD_CONF} &

# Wait for clamd to be ready
echo "Waiting for clamd to load virus definitions..."
max_wait=180
waited=0
while ! clamdscan --config-file=${CLAMD_CONF} --ping 1 2>/dev/null; do
    if [ $waited -ge $max_wait ]; then
        echo "Error: clamd failed to start within ${max_wait}s"
        if [ -f /var/log/clamav/clamd.log ]; then
            echo "clamd.log tail:"
            tail -20 /var/log/clamav/clamd.log
        fi
        exit 1
    fi
    sleep 2
    waited=$((waited + 2))
    echo "  Waiting... (${waited}s)"
done
echo "clamd is ready!"

# Drop privileges and start REST server as non-root user
echo "Starting ClamAV REST server on port ${PORT:-9000} as user 'scanner'..."
if command -v gosu >/dev/null 2>&1; then
    exec gosu scanner ./clamav-rest
elif command -v su-exec >/dev/null 2>&1; then
    exec su-exec scanner ./clamav-rest
else
    # Fallback: run directly (less secure, but works)
    exec su -s /bin/sh scanner -c './clamav-rest'
fi
